const assert=require('node:assert/strict'),path=require('node:path');
const {startFixture}=require('../tests/helpers/lan-browser-fixture.cjs');
const {chromium}=require(process.env.BP_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
  const fixture=await startFixture();let browser;
  try{
    browser=await chromium.launch({headless:true,executablePath:process.env.BP_CHROMIUM});
    const errors=[],requests=[];
    const admin=await browser.newPage({viewport:{width:1280,height:960}});admin.on('pageerror',e=>errors.push(e.message));admin.on('request',r=>requests.push(r.url()));
    await admin.goto(fixture.adminOrigin);await admin.locator('#open').waitFor();await admin.locator('#open').click();
    await admin.locator('#exit-project').waitFor();await admin.locator('#qr svg').waitFor();
    assert.equal(fixture.store.sessions().length,1);await admin.screenshot({path:'docs/web-projector.png',fullPage:true});
    const mobile=await browser.newPage({viewport:{width:390,height:844}});mobile.on('pageerror',e=>errors.push(e.message));mobile.on('request',r=>requests.push(r.url()));
    await mobile.goto(fixture.origin);await mobile.locator('#attendance-form').waitFor();
    assert.equal(await mobile.locator('input').count(),3);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await mobile.screenshot({path:'docs/web-student-ready.png',fullPage:true});
    await mobile.locator('#student-id').fill('001');await mobile.locator('#full-name').fill('Nguyễn An');await mobile.locator('#seat').fill('B-12');
    let attempted=0;await mobile.route('**/api/check-in',async route=>{if(++attempted===1)return route.abort('failed');await route.fetch();await route.abort('failed');});
    await mobile.locator('#submit').click();await mobile.waitForFunction(()=>document.getElementById('notice').textContent.includes('Chưa xác nhận được'));
    assert.equal(await mobile.locator('#receipt').isVisible(),false);assert.equal(fixture.store.entries().length,0);
    await mobile.locator('#submit').click();await mobile.waitForFunction(()=>document.getElementById('notice').textContent.includes('Chưa xác nhận được'));
    assert.equal(fixture.store.entries().length,1);assert.equal(await mobile.locator('#receipt').isVisible(),false);
    await mobile.unroute('**/api/check-in');await mobile.reload();await mobile.locator('#submit').click();await mobile.locator('#receipt').waitFor();
    assert.match(await mobile.locator('#receipt').textContent(),/001/);assert.match(await mobile.locator('#notice').textContent(),/trước đó/);
    await mobile.screenshot({path:'docs/web-student.png',fullPage:true});
    const desktop=await browser.newPage({viewport:{width:1200,height:900}});desktop.on('pageerror',e=>errors.push(e.message));await desktop.goto(fixture.origin);
    await desktop.locator('#student-id').fill('002');await desktop.locator('#full-name').fill('Trần Bình');await desktop.locator('#seat').fill('B-13');
    await desktop.screenshot({path:'docs/web-student-desktop.png',fullPage:true});await desktop.locator('#submit').click();await desktop.locator('#receipt').waitFor();
    await admin.locator('#exit-project').click();await admin.waitForFunction(()=>document.querySelectorAll('#entries tr.flagged').length===2,{},{timeout:15000});
    await admin.screenshot({path:'docs/web-admin.png',fullPage:true});
    await admin.locator('#entries button').first().click();await admin.locator('#review-note').fill('Đã đối chiếu thẻ sinh viên và người ngồi ghế B-12.');
    await admin.screenshot({path:'docs/web-review.png',fullPage:true});await admin.locator('#save-review').click();await admin.waitForFunction(()=>document.querySelectorAll('#entries tr.flagged').length===1);
    assert.equal(fixture.store.entries()[0].status,'CONFIRMED');await admin.locator('#close').click();await admin.waitForFunction(()=>!document.querySelector('#qr svg'));
    const closed=await browser.newPage();await closed.goto(fixture.origin);await closed.waitForFunction(()=>document.getElementById('notice').textContent.includes('Chưa mở điểm danh'));
    assert.equal(await closed.locator('#attendance-form').isVisible(),false);
    assert.deepEqual(errors,[]);assert.ok(requests.every(url=>url.startsWith(fixture.origin)||url.startsWith(fixture.adminOrigin)));
    assert.doesNotMatch(await admin.locator('body').innerText(),/demo|minh họa|dữ liệu giả/i);
    console.log('LAN UI passed: three-field mobile/desktop form, QR projection, network loss before/after commit, reload recovery, both IP peers red, TA review, closed window, local assets and screenshots.');
  }finally{if(browser)await browser.close();await fixture.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
