const assert=require('node:assert/strict'),fs=require('node:fs');
const {randomBytes}=require('node:crypto');
const {today}=require('../web/security.cjs');
const {parse}=require('csv-parse/sync');
const {startFixture}=require('../tests/helpers/lan-browser-fixture.cjs');
const {chromium}=require(process.env.BP_PLAYWRIGHT_MODULE||'playwright');
const screenshotDirectory=require('node:path').resolve(process.env.BP_SCREENSHOT_DIR||'docs');
fs.mkdirSync(screenshotDirectory,{recursive:true});
const screenshot=(page,name)=>page.screenshot({path:require('node:path').join(screenshotDirectory,name),fullPage:true});
(async()=>{
  const fixture=await startFixture();let browser;
  try{
    browser=await chromium.launch({headless:true,executablePath:process.env.BP_CHROMIUM});
    const picker=await require('./network-picker.cjs').networkPicker({list:()=>[{name:'Wi-Fi',address:'192.168.2.20',cidr:'192.168.2.20/24',wifi:true}]});
    try{
      const page=await browser.newPage({viewport:{width:1000,height:850}});await page.goto(picker.origin);await page.locator('.network-option').waitFor();await screenshot(page,'web-network-picker.png');
      await page.locator('.network-option').click();assert.equal((await picker.selection).name,'Wi-Fi');picker.finish(fixture.adminOrigin+'/');await page.waitForURL(fixture.adminOrigin+'/');await page.close();
    }finally{await picker.close();}
    const errors=[],requests=[];
    function watch(page){page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));}
    const taContext=await browser.newContext({viewport:{width:1280,height:960}});
    let admin=await taContext.newPage();watch(admin);
    await admin.goto(fixture.adminOrigin);await admin.locator('#open').waitFor();
    const popup=admin.waitForEvent('popup');await admin.locator('#open').click();
    const projector=await popup;watch(projector);await projector.waitForURL(fixture.adminOrigin+'/projector/');
    await projector.locator('#qr svg').waitFor();await admin.waitForFunction(()=>!busy);
    assert.equal(await admin.locator('#entries').isVisible(),true,'TA controls remain visible in the original tab');
    assert.equal(fixture.store.sessions().length,1);await projector.setViewportSize({width:1280,height:720});
    assert.ok(await projector.evaluate(()=>document.documentElement.scrollHeight<=innerHeight),'QR and room code must fit a 720p projector without scrolling');
    assert.ok(await projector.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await screenshot(projector,'web-projector.png');
    await projector.locator('#fullscreen').click();await projector.waitForFunction(()=>!!document.fullscreenElement);
    assert.match(await projector.locator('#fullscreen').textContent(),/Thoát/);
    await projector.locator('#fullscreen').click();await projector.waitForFunction(()=>!document.fullscreenElement);
    const pagesBefore=admin.context().pages().length;await admin.locator('#project').click();assert.equal(admin.context().pages().length,pagesBefore,'Chiếu QR reuses the existing projection tab');
    // The projection must keep rotating with the TA tab closed, without postMessage or opener state.
    const firstQr=fixture.store.currentQr(),firstCode=await projector.locator('#attendance-code').textContent();
    await admin.close();
    await projector.waitForFunction(code=>document.getElementById('attendance-code').textContent&&document.getElementById('attendance-code').textContent!==code,firstCode,{timeout:35000});
    // Hide the code on a connection error, then recover automatically.
    await projector.route('**/api/projector',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));
    await projector.waitForFunction(()=>document.getElementById('session-state').textContent==='MẤT KẾT NỐI');
    assert.equal(await projector.locator('#qr svg').count(),0);assert.equal(await projector.locator('#attendance-code').textContent(),'');
    await projector.unroute('**/api/projector');await projector.locator('#qr svg').waitFor();
    admin=await taContext.newPage();watch(admin);await admin.goto(fixture.adminOrigin);await admin.waitForFunction(()=>!busy);
    const expired=await fetch(fixture.origin+'/api/scan',{method:'POST',headers:{Origin:fixture.origin,'Content-Type':'application/json'},body:JSON.stringify({token:firstQr.token})});assert.equal(expired.status,410);
    const mobile=await browser.newPage({viewport:{width:390,height:844}});mobile.on('pageerror',e=>errors.push(e.message));mobile.on('request',r=>requests.push(r.url()));
    const qrLink=()=>fixture.origin+'/#code='+fixture.store.currentQr().code;
    await mobile.goto(qrLink());await mobile.locator('#attendance-form').waitFor();
    assert.equal(await mobile.locator('#attendance-form input').count(),3);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    assert.equal(await mobile.locator('#location-section').isVisible(),false,'Normal attendance must not ask for location');
    assert.equal(await mobile.locator('#scan-form').isVisible(),false);assert.equal(new URL(mobile.url()).hash,'');
    await screenshot(mobile,'web-student-ready.png');
    await mobile.locator('#student-id').fill('001');await mobile.locator('#full-name').fill('Nguyễn An');await mobile.locator('#seat').fill('B-12');
    let attempted=0;await mobile.route('**/api/check-in',async route=>{if(++attempted===1)return route.abort('failed');await route.fetch();await route.abort('failed');});
    await mobile.locator('#submit').click();await mobile.waitForFunction(()=>document.getElementById('notice').textContent.includes('Chưa xác nhận được'));
    assert.equal(await mobile.locator('#receipt').isVisible(),false);assert.equal(fixture.store.entries().length,0);
    await mobile.locator('#submit').click();await mobile.waitForFunction(()=>document.getElementById('notice').textContent.includes('Chưa xác nhận được'));
    assert.equal(fixture.store.entries().length,1);assert.equal(await mobile.locator('#receipt').isVisible(),false);
    await mobile.unroute('**/api/check-in');await mobile.reload();await mobile.locator('#submit').click();await mobile.locator('#receipt').waitFor();
    assert.match(await mobile.locator('#receipt').textContent(),/001/);assert.match(await mobile.locator('#notice').textContent(),/trước đó/);
    await screenshot(mobile,'web-student.png');
    const desktop=await browser.newPage({viewport:{width:1200,height:900}});desktop.on('pageerror',e=>errors.push(e.message));await desktop.goto(fixture.origin);
    await desktop.locator('#scan-form').waitFor();assert.equal(await desktop.locator('#attendance-form').isVisible(),false);
    await screenshot(desktop,'web-student-code.png');
    await desktop.locator('#room-code').fill(fixture.store.currentQr().code);await desktop.locator('#scan-submit').click();await desktop.locator('#attendance-form').waitFor();
    await desktop.locator('#student-id').fill('002');await desktop.locator('#full-name').fill('Trần Bình');await desktop.locator('#seat').fill('B-13');
    await screenshot(desktop,'web-student-desktop.png');await desktop.locator('#submit').click();await desktop.locator('#receipt').waitFor();
    await admin.waitForFunction(()=>document.querySelectorAll('#entries tr.flagged').length===2,{},{timeout:15000});
    await projector.waitForFunction(()=>document.getElementById('count').textContent==='2 sinh viên đã gửi');
    await screenshot(admin,'web-admin.png');
    await admin.locator('#attendance-ip').selectOption('DUPLICATE');await admin.locator('#attendance-q').fill('001');
    await admin.waitForFunction(()=>document.querySelectorAll('#entries tr[data-entry-id]').length===1&&!busy);
    assert.match(await admin.locator('#entries').textContent(),/2 MSSV/,'Filtering one student must retain the full IP group count');
    const filteredDownload=admin.waitForEvent('download');await admin.locator('#attendance-export').click();const filteredFile=await filteredDownload;
    assert.deepEqual(parse(fs.readFileSync(await filteredFile.path(),'utf8'),{bom:true}).slice(1).map(r=>r[1]),['001']);
    await screenshot(admin,'web-ta-filters.png');
    await admin.locator('#attendance-location').selectOption('INSIDE');await admin.waitForFunction(()=>!busy&&document.querySelector('#entries').textContent.includes('Không có bản ghi phù hợp'));
    await admin.locator('#attendance-reset').click();await admin.waitForFunction(()=>document.querySelectorAll('#entries tr[data-entry-id]').length===2&&!busy);
    await admin.locator('#entries button').first().click();await admin.locator('#review-note').fill('Đã đối chiếu thẻ sinh viên và người ngồi ghế B-12.');
    await screenshot(admin,'web-review.png');await admin.locator('#save-review').click();await admin.waitForFunction(()=>document.querySelectorAll('#entries tr.flagged').length===1);
    assert.equal(fixture.store.entries()[0].status,'CONFIRMED');
    const currentDate=fixture.store.sessions()[0].date,previousTime=Date.now()-7*86400000,previousDate=today(previousTime);
    const previous=fixture.store.open(previousDate,8,'TA kiểm thử',previousTime);
    for(const id of ['001','099'])fixture.store.submit({sessionId:previous.id,studentId:id,name:id==='001'?'Nguyễn An':'Lê Minh',seat:id==='001'?'A-02':'A-03',requestId:randomBytes(16).toString('hex')},'127.0.0.1',previousTime);
    const previousRejected=fixture.store.entries(previous.id).find(e=>e.student_id==='099');fixture.store.reviewEntry(previousRejected.id,'REJECTED','Không có mặt tại ghế A-03 khi đối chiếu.',2,'TA kiểm thử',previousTime+1000);
    async function navigate(name){await admin.locator('.screen-nav a[href="#'+name+'"]').click();await admin.waitForFunction(()=>!busy);}
    async function download(id){const pending=admin.waitForEvent('download');await admin.locator('#'+id).click();const file=await pending;return {name:file.suggestedFilename(),rows:parse(fs.readFileSync(await file.path(),'utf8'),{bom:true})};}
    await navigate('issues');await admin.waitForFunction(()=>document.querySelectorAll('#issues-entries tr[data-entry-id]').length===3);
    assert.match(await admin.locator('#issues-pending').textContent(),/2 chờ đối chiếu/);assert.match(await admin.locator('#issues-rejected').textContent(),/1 không hợp lệ/);
    await screenshot(admin,'web-cases.png');
    await admin.locator('#issues-status').selectOption('REJECTED');await admin.waitForFunction(()=>document.querySelectorAll('#issues-entries tr[data-entry-id]').length===1&&!busy);
    const cases=await download('issues-export');assert.match(cases.name,/all_rejected\.csv$/);assert.equal(cases.rows.length,2);assert.equal(cases.rows[1][1],'099');
    await admin.locator('#issues-date').selectOption(currentDate);await admin.waitForFunction(()=>!busy);assert.match(await admin.locator('#issues-entries').textContent(),/Không có bản ghi phù hợp/);
    await admin.locator('#issues-status').selectOption('ALL');await admin.waitForFunction(()=>document.querySelectorAll('#issues-entries tr[data-entry-id]').length===1&&!busy);
    await admin.locator('#issues-entries button').click();await admin.locator('#review-note').fill('Không có mặt tại ghế B-13 khi đối chiếu.');await admin.locator('#review-result').selectOption('REJECTED');await admin.locator('#save-review').click();
    await admin.waitForFunction(()=>document.querySelector('#issues-entries tr.rejected'));
    await navigate('history');await admin.waitForFunction(()=>document.querySelectorAll('#history-entries tr[data-entry-id]').length===4&&!busy);
    await admin.locator('#history-q').fill('099');await admin.locator('#history-status').selectOption('REJECTED');
    await admin.waitForFunction(()=>document.querySelectorAll('#history-entries tr[data-entry-id]').length===1&&!busy);
    const filteredHistory=await download('history-detail-export');assert.deepEqual(filteredHistory.rows.slice(1).map(r=>r[1]),['099']);
    await admin.locator('#history-reset').click();await admin.waitForFunction(()=>document.querySelectorAll('#history-entries tr[data-entry-id]').length===4&&!busy);
    await screenshot(admin,'web-history.png');
    const all=await download('history-summary-export');assert.deepEqual(all.rows[0].slice(3),[previousDate,currentDate]);assert.equal(all.rows.length,4);assert.match(all.name,/all\.csv$/);
    await admin.locator('#history-date').selectOption(currentDate);await admin.waitForFunction(()=>document.querySelectorAll('#history-entries tr[data-entry-id]').length===2&&!busy);
    const day=await download('history-summary-export');assert.equal(day.name,'BP_Attendance_'+currentDate+'.csv');assert.deepEqual(day.rows[0].slice(3),[currentDate]);assert.deepEqual(day.rows.slice(1).map(r=>r[0]),['001','002']);
    const detail=await download('history-detail-export');assert.equal(detail.rows.length,3);assert.ok(detail.rows.slice(1).every(r=>r[0]===currentDate));assert.match(detail.rows[2][7],/ghế B-13/);
    await admin.locator('#history-date').selectOption(previousDate);await admin.waitForFunction(()=>!busy);assert.match(await admin.locator('#history-entries').textContent(),/099/);assert.doesNotMatch(await admin.locator('#history-entries').textContent(),/002/);
    await admin.reload();await admin.waitForFunction(()=>!busy);assert.equal(await admin.locator('#screen-history').isVisible(),true);assert.equal(await admin.locator('#screen-attendance').isVisible(),false);
    await navigate('attendance');await admin.locator('#close').click();await admin.waitForFunction(()=>!document.querySelector('#qr svg'));
    await projector.waitForFunction(()=>document.getElementById('session-state').textContent==='ĐỢT ĐÃ ĐÓNG');
    assert.equal(await projector.locator('#qr svg').count(),0);assert.equal(await projector.locator('#attendance-code').textContent(),'');
    const closed=await browser.newPage();await closed.goto(fixture.origin);await closed.waitForFunction(()=>document.getElementById('notice').textContent.includes('Chưa mở điểm danh'));
    assert.equal(await closed.locator('#attendance-form').isVisible(),false);
    // Reopen the same round: existing receipts stay valid and no new record is created.
    await admin.locator('#reopen').click();await admin.waitForFunction(()=>!busy);
    await mobile.locator('#reload').click();await mobile.locator('#receipt').waitFor();
    assert.match(await mobile.locator('#receipt-fields').textContent(),/Đợt 1/);
    assert.equal(fixture.store.entries().length,4);
    await admin.locator('#close').click();await admin.waitForFunction(()=>!busy);
    // A new round is a new check-in, even on the same phone with an old receipt.
    await admin.locator('#round-label').fill('Giữa giờ');await admin.locator('#open').click();await admin.waitForFunction(()=>!busy);
    const roundTwo=fixture.store.activeSession();assert.equal(roundTwo.number,2);assert.equal(roundTwo.label,'Giữa giờ');
    await mobile.goto(qrLink());await mobile.locator('#attendance-form').waitFor();
    assert.equal(await mobile.locator('#receipt').isVisible(),false);assert.match(await mobile.locator('#date').textContent(),/Đợt 2 · Giữa giờ/);
    assert.equal(await mobile.locator('#student-id').inputValue(),'001');await mobile.locator('#submit').click();await mobile.locator('#receipt').waitFor();
    assert.match(await mobile.locator('#receipt-fields').textContent(),/Đợt 2 · Giữa giờ/);assert.equal(fixture.store.entries(roundTwo.id).length,1);
    await admin.reload();await admin.waitForFunction(()=>!busy);await admin.locator('#session').selectOption(roundTwo.id);await admin.waitForFunction(()=>!busy);
    assert.match(await admin.locator('#round-title').textContent(),/Đợt 2 · Giữa giờ/);
    await screenshot(admin,'web-rounds.png');await screenshot(mobile,'web-student-round.png');
    const dayMatrix=fixture.store.report('summary',currentDate).csv;assert.match(dayMatrix,/Đã gửi 2\/2 đợt/);assert.match(dayMatrix,/Đã gửi 1\/2 đợt/);
    await navigate('history');await admin.locator('#history-date').selectOption(currentDate);await admin.waitForFunction(()=>!busy);
    const multiRound=await download('history-detail-export');assert.equal(multiRound.rows.length,4);assert.equal(multiRound.rows.at(-1)[11],'2');assert.equal(multiRound.rows.at(-1)[12],'Giữa giờ');
    // Reopening an older round must recall its own receipt, not the newer round's.
    fixture.store.closeSession(roundTwo.id,'TA');const roundOne=fixture.store.sessions().find(s=>s.date===currentDate&&s.number===1);fixture.store.reopen(roundOne.id,8,'TA');
    await mobile.goto(qrLink());await mobile.locator('#receipt').waitFor();assert.match(await mobile.locator('#receipt-fields').textContent(),/Đợt 1/);
    assert.equal(fixture.store.entries(roundOne.id).length,2);assert.equal(fixture.store.entries(roundTwo.id).length,1);
    // Older embedded browsers: no new timeout/fetch/DOM APIs, and storage denied.
    const older=await browser.newContext({viewport:{width:390,height:844}});
    await older.addInitScript(()=>{
      window.fetch=undefined;window.AbortSignal=undefined;window.AbortController=undefined;window.URLSearchParams=undefined;
      Element.prototype.replaceChildren=undefined;
      Storage.prototype.getItem=function(){throw Error('Storage unavailable');};Storage.prototype.setItem=function(){throw Error('Storage unavailable');};
    });
    const compatible=await older.newPage();watch(compatible);
    await compatible.route('**/api/session',route=>route.abort('failed'));
    await compatible.goto(qrLink());await compatible.locator('#attendance-form').waitFor();
    await compatible.locator('#student-id').fill('COMPAT01');await compatible.locator('#full-name').fill('Kiểm tra trình duyệt');await compatible.locator('#seat').fill('C-01');
    await compatible.route('**/api/check-in',async route=>{await route.fetch();await route.abort('failed');});
    await compatible.locator('#submit').click();await compatible.waitForFunction(()=>document.getElementById('notice').textContent.includes('Chưa xác nhận được'));
    const beforeRetry=fixture.store.entries().length;await compatible.unroute('**/api/check-in');await compatible.unroute('**/api/session');
    await compatible.locator('#reload').click();await compatible.waitForFunction(()=>!document.getElementById('reload').disabled);
    await compatible.locator('#submit').click();await compatible.locator('#receipt').waitFor();
    assert.equal(fixture.store.entries().length,beforeRetry);assert.match(await compatible.locator('#receipt').textContent(),/COMPAT01/);
    const retryScan=await browser.newPage();watch(retryScan);await retryScan.route('**/api/scan',route=>route.abort('failed'));
    await retryScan.goto(qrLink());await retryScan.waitForFunction(()=>document.getElementById('notice').classList.contains('error'));
    assert.ok(new URL(retryScan.url()).hash.startsWith('#code='),'transport failures retain the QR for retry');
    await retryScan.unroute('**/api/scan');await retryScan.locator('#reload').click();await retryScan.locator('#attendance-form').waitFor();assert.equal(new URL(retryScan.url()).hash,'');
    // The lookup reads only TA Sheet results, including a change after initial publication.
    fixture.lookup.fetchValues=async()=>[['MSSV','Họ tên','Email trường','2026-09-09','2026-09-16'],['001','Not for public lookup','private@example.invalid','OFF','Đã gửi 2/3 đợt']];
    await navigate('history');await admin.locator('#lookup-sheet').fill('https://docs.google.com/spreadsheets/d/abcdefghijklmnop12345/edit#gid=0');await admin.locator('#lookup-tab').fill('Offline');
    await admin.locator('#lookup-save').click();await admin.waitForFunction(()=>!busy);while(fixture.lookup.busy)await fixture.lookup.busy;
    const historyPage=await older.newPage();watch(historyPage);await historyPage.goto(fixture.origin+'/history');await historyPage.locator('#lookup-id').fill('001');await historyPage.locator('#lookup-submit').click();await historyPage.locator('#lookup-result').waitFor();
    assert.match(await historyPage.locator('#lookup-rows').textContent(),/Đã gửi 2\/3 đợt/);assert.doesNotMatch(await historyPage.locator('body').innerText(),/Not for public lookup|private@example|C-01/);
    assert.ok(await historyPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await screenshot(historyPage,'web-student-history.png');
    fixture.lookup.fetchValues=async()=>[['MSSV','2026-09-16'],['001','TA đã xác nhận']];
    const refreshed=admin.waitForResponse(r=>r.url().endsWith('/api/lookup-refresh'));await admin.locator('#lookup-refresh').click();await refreshed;while(fixture.lookup.busy)await fixture.lookup.busy;
    await historyPage.locator('#lookup-submit').click();await historyPage.waitForFunction(()=>document.getElementById('lookup-rows').textContent.includes('TA đã xác nhận'));
    fixture.lookup.fetchValues=async()=>{throw Error('network unavailable');};await fixture.lookup.sync();
    await historyPage.locator('#lookup-submit').click();await historyPage.waitForFunction(()=>document.getElementById('lookup-notice').textContent.includes('Chưa lấy được bản cập nhật'));
    assert.match(await historyPage.locator('#lookup-rows').textContent(),/TA đã xác nhận/);
    assert.deepEqual(errors,[]);assert.ok(requests.every(url=>url.startsWith(fixture.origin)||url.startsWith(fixture.adminOrigin)));
    assert.doesNotMatch(await admin.locator('body').innerText(),/demo|minh họa|dữ liệu giả/i);
    console.log('LAN UI passed: legacy browser APIs/storage, immediate QR admission, lost scan retry, read-only Sheet history with refreshed/stale results, same-day new/reopened rounds, per-round receipts, independent fullscreen projection, QR rotation/expiry, network loss before/after commit, peer review, CSV reports and screenshots.');
  }finally{if(browser)await browser.close();await fixture.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
